name: Lint and Test Charts

on:
  pull_request:
  push:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: OpensStack Helm Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: openstack-helm

      - name: OpenStack Helm Infra Checkout
        uses: actions/checkout@v4
        with:
          repository: openstack/openstack-helm-infra
          ref: master
          fetch-depth: 0
          path: openstack-helm-infra

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          cd openstack-helm
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          cd openstack-helm
          ct lint --chart-dirs=. --validate-maintainers=false --target-branch ${{ github.event.repository.default_branch }}
